# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dominic/CLionProjects/PRISM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dominic/CLionProjects/PRISM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominic/CLionProjects/PRISM/CMakeFiles /home/dominic/CLionProjects/FASTER//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominic/CLionProjects/PRISM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PRISM

# Build rule for target.
PRISM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PRISM
.PHONY : PRISM

# fast build rule for target.
PRISM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PRISM.dir/build.make CMakeFiles/FASTER.dir/build
.PHONY : FASTER/fast

Communities/Communities.o: Communities/Communities.cpp.o
.PHONY : Communities/Communities.o

# target to build an object file
Communities/Communities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Communities.cpp.o
.PHONY : Communities/Communities.cpp.o

Communities/Communities.i: Communities/Communities.cpp.i
.PHONY : Communities/Communities.i

# target to preprocess a source file
Communities/Communities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Communities.cpp.i
.PHONY : Communities/Communities.cpp.i

Communities/Communities.s: Communities/Communities.cpp.s
.PHONY : Communities/Communities.s

# target to generate assembly for a file
Communities/Communities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Communities.cpp.s
.PHONY : Communities/Communities.cpp.s

Communities/Community.o: Communities/Community.cpp.o
.PHONY : Communities/Community.o

# target to build an object file
Communities/Community.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Community.cpp.o
.PHONY : Communities/Community.cpp.o

Communities/Community.i: Communities/Community.cpp.i
.PHONY : Communities/Community.i

# target to preprocess a source file
Communities/Community.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Community.cpp.i
.PHONY : Communities/Community.cpp.i

Communities/Community.s: Communities/Community.cpp.s
.PHONY : Communities/Community.s

# target to generate assembly for a file
Communities/Community.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/Community.cpp.s
.PHONY : Communities/Community.cpp.s

Communities/CommunityPrinter.o: Communities/CommunityPrinter.cpp.o
.PHONY : Communities/CommunityPrinter.o

# target to build an object file
Communities/CommunityPrinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/CommunityPrinter.cpp.o
.PHONY : Communities/CommunityPrinter.cpp.o

Communities/CommunityPrinter.i: Communities/CommunityPrinter.cpp.i
.PHONY : Communities/CommunityPrinter.i

# target to preprocess a source file
Communities/CommunityPrinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/CommunityPrinter.cpp.i
.PHONY : Communities/CommunityPrinter.cpp.i

Communities/CommunityPrinter.s: Communities/CommunityPrinter.cpp.s
.PHONY : Communities/CommunityPrinter.s

# target to generate assembly for a file
Communities/CommunityPrinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Communities/CommunityPrinter.cpp.s
.PHONY : Communities/CommunityPrinter.cpp.s

Graphs/HierarchicalClusterer.o: Graphs/HierarchicalClusterer.cpp.o
.PHONY : Graphs/HierarchicalClusterer.o

# target to build an object file
Graphs/HierarchicalClusterer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HierarchicalClusterer.cpp.o
.PHONY : Graphs/HierarchicalClusterer.cpp.o

Graphs/HierarchicalClusterer.i: Graphs/HierarchicalClusterer.cpp.i
.PHONY : Graphs/HierarchicalClusterer.i

# target to preprocess a source file
Graphs/HierarchicalClusterer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HierarchicalClusterer.cpp.i
.PHONY : Graphs/HierarchicalClusterer.cpp.i

Graphs/HierarchicalClusterer.s: Graphs/HierarchicalClusterer.cpp.s
.PHONY : Graphs/HierarchicalClusterer.s

# target to generate assembly for a file
Graphs/HierarchicalClusterer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HierarchicalClusterer.cpp.s
.PHONY : Graphs/HierarchicalClusterer.cpp.s

Graphs/HyperGraph.o: Graphs/HyperGraph.cpp.o
.PHONY : Graphs/HyperGraph.o

# target to build an object file
Graphs/HyperGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HyperGraph.cpp.o
.PHONY : Graphs/HyperGraph.cpp.o

Graphs/HyperGraph.i: Graphs/HyperGraph.cpp.i
.PHONY : Graphs/HyperGraph.i

# target to preprocess a source file
Graphs/HyperGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HyperGraph.cpp.i
.PHONY : Graphs/HyperGraph.cpp.i

Graphs/HyperGraph.s: Graphs/HyperGraph.cpp.s
.PHONY : Graphs/HyperGraph.s

# target to generate assembly for a file
Graphs/HyperGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/HyperGraph.cpp.s
.PHONY : Graphs/HyperGraph.cpp.s

Graphs/UndirectedGraph.o: Graphs/UndirectedGraph.cpp.o
.PHONY : Graphs/UndirectedGraph.o

# target to build an object file
Graphs/UndirectedGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/UndirectedGraph.cpp.o
.PHONY : Graphs/UndirectedGraph.cpp.o

Graphs/UndirectedGraph.i: Graphs/UndirectedGraph.cpp.i
.PHONY : Graphs/UndirectedGraph.i

# target to preprocess a source file
Graphs/UndirectedGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/UndirectedGraph.cpp.i
.PHONY : Graphs/UndirectedGraph.cpp.i

Graphs/UndirectedGraph.s: Graphs/UndirectedGraph.cpp.s
.PHONY : Graphs/UndirectedGraph.s

# target to generate assembly for a file
Graphs/UndirectedGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Graphs/UndirectedGraph.cpp.s
.PHONY : Graphs/UndirectedGraph.cpp.s

RandomWalker/NodeClusterRandomWalkData.o: RandomWalker/NodeClusterRandomWalkData.cpp.o
.PHONY : RandomWalker/NodeClusterRandomWalkData.o

# target to build an object file
RandomWalker/NodeClusterRandomWalkData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeClusterRandomWalkData.cpp.o
.PHONY : RandomWalker/NodeClusterRandomWalkData.cpp.o

RandomWalker/NodeClusterRandomWalkData.i: RandomWalker/NodeClusterRandomWalkData.cpp.i
.PHONY : RandomWalker/NodeClusterRandomWalkData.i

# target to preprocess a source file
RandomWalker/NodeClusterRandomWalkData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeClusterRandomWalkData.cpp.i
.PHONY : RandomWalker/NodeClusterRandomWalkData.cpp.i

RandomWalker/NodeClusterRandomWalkData.s: RandomWalker/NodeClusterRandomWalkData.cpp.s
.PHONY : RandomWalker/NodeClusterRandomWalkData.s

# target to generate assembly for a file
RandomWalker/NodeClusterRandomWalkData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeClusterRandomWalkData.cpp.s
.PHONY : RandomWalker/NodeClusterRandomWalkData.cpp.s

RandomWalker/NodeRandomWalkData.o: RandomWalker/NodeRandomWalkData.cpp.o
.PHONY : RandomWalker/NodeRandomWalkData.o

# target to build an object file
RandomWalker/NodeRandomWalkData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeRandomWalkData.cpp.o
.PHONY : RandomWalker/NodeRandomWalkData.cpp.o

RandomWalker/NodeRandomWalkData.i: RandomWalker/NodeRandomWalkData.cpp.i
.PHONY : RandomWalker/NodeRandomWalkData.i

# target to preprocess a source file
RandomWalker/NodeRandomWalkData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeRandomWalkData.cpp.i
.PHONY : RandomWalker/NodeRandomWalkData.cpp.i

RandomWalker/NodeRandomWalkData.s: RandomWalker/NodeRandomWalkData.cpp.s
.PHONY : RandomWalker/NodeRandomWalkData.s

# target to generate assembly for a file
RandomWalker/NodeRandomWalkData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/NodeRandomWalkData.cpp.s
.PHONY : RandomWalker/NodeRandomWalkData.cpp.s

RandomWalker/RandomWalker.o: RandomWalker/RandomWalker.cpp.o
.PHONY : RandomWalker/RandomWalker.o

# target to build an object file
RandomWalker/RandomWalker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/RandomWalker.cpp.o
.PHONY : RandomWalker/RandomWalker.cpp.o

RandomWalker/RandomWalker.i: RandomWalker/RandomWalker.cpp.i
.PHONY : RandomWalker/RandomWalker.i

# target to preprocess a source file
RandomWalker/RandomWalker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/RandomWalker.cpp.i
.PHONY : RandomWalker/RandomWalker.cpp.i

RandomWalker/RandomWalker.s: RandomWalker/RandomWalker.cpp.s
.PHONY : RandomWalker/RandomWalker.s

# target to generate assembly for a file
RandomWalker/RandomWalker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/RandomWalker/RandomWalker.cpp.s
.PHONY : RandomWalker/RandomWalker.cpp.s

UnitTests/run_all_tests.o: UnitTests/run_all_tests.cpp.o
.PHONY : UnitTests/run_all_tests.o

# target to build an object file
UnitTests/run_all_tests.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/run_all_tests.cpp.o
.PHONY : UnitTests/run_all_tests.cpp.o

UnitTests/run_all_tests.i: UnitTests/run_all_tests.cpp.i
.PHONY : UnitTests/run_all_tests.i

# target to preprocess a source file
UnitTests/run_all_tests.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/run_all_tests.cpp.i
.PHONY : UnitTests/run_all_tests.cpp.i

UnitTests/run_all_tests.s: UnitTests/run_all_tests.cpp.s
.PHONY : UnitTests/run_all_tests.s

# target to generate assembly for a file
UnitTests/run_all_tests.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/run_all_tests.cpp.s
.PHONY : UnitTests/run_all_tests.cpp.s

UnitTests/test_clustering.o: UnitTests/test_clustering.cpp.o
.PHONY : UnitTests/test_clustering.o

# target to build an object file
UnitTests/test_clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_clustering.cpp.o
.PHONY : UnitTests/test_clustering.cpp.o

UnitTests/test_clustering.i: UnitTests/test_clustering.cpp.i
.PHONY : UnitTests/test_clustering.i

# target to preprocess a source file
UnitTests/test_clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_clustering.cpp.i
.PHONY : UnitTests/test_clustering.cpp.i

UnitTests/test_clustering.s: UnitTests/test_clustering.cpp.s
.PHONY : UnitTests/test_clustering.s

# target to generate assembly for a file
UnitTests/test_clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_clustering.cpp.s
.PHONY : UnitTests/test_clustering.cpp.s

UnitTests/test_communities.o: UnitTests/test_communities.cpp.o
.PHONY : UnitTests/test_communities.o

# target to build an object file
UnitTests/test_communities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_communities.cpp.o
.PHONY : UnitTests/test_communities.cpp.o

UnitTests/test_communities.i: UnitTests/test_communities.cpp.i
.PHONY : UnitTests/test_communities.i

# target to preprocess a source file
UnitTests/test_communities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_communities.cpp.i
.PHONY : UnitTests/test_communities.cpp.i

UnitTests/test_communities.s: UnitTests/test_communities.cpp.s
.PHONY : UnitTests/test_communities.s

# target to generate assembly for a file
UnitTests/test_communities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_communities.cpp.s
.PHONY : UnitTests/test_communities.cpp.s

UnitTests/test_graphs.o: UnitTests/test_graphs.cpp.o
.PHONY : UnitTests/test_graphs.o

# target to build an object file
UnitTests/test_graphs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_graphs.cpp.o
.PHONY : UnitTests/test_graphs.cpp.o

UnitTests/test_graphs.i: UnitTests/test_graphs.cpp.i
.PHONY : UnitTests/test_graphs.i

# target to preprocess a source file
UnitTests/test_graphs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_graphs.cpp.i
.PHONY : UnitTests/test_graphs.cpp.i

UnitTests/test_graphs.s: UnitTests/test_graphs.cpp.s
.PHONY : UnitTests/test_graphs.s

# target to generate assembly for a file
UnitTests/test_graphs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_graphs.cpp.s
.PHONY : UnitTests/test_graphs.cpp.s

UnitTests/test_hierarchical_clustering.o: UnitTests/test_hierarchical_clustering.cpp.o
.PHONY : UnitTests/test_hierarchical_clustering.o

# target to build an object file
UnitTests/test_hierarchical_clustering.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_hierarchical_clustering.cpp.o
.PHONY : UnitTests/test_hierarchical_clustering.cpp.o

UnitTests/test_hierarchical_clustering.i: UnitTests/test_hierarchical_clustering.cpp.i
.PHONY : UnitTests/test_hierarchical_clustering.i

# target to preprocess a source file
UnitTests/test_hierarchical_clustering.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_hierarchical_clustering.cpp.i
.PHONY : UnitTests/test_hierarchical_clustering.cpp.i

UnitTests/test_hierarchical_clustering.s: UnitTests/test_hierarchical_clustering.cpp.s
.PHONY : UnitTests/test_hierarchical_clustering.s

# target to generate assembly for a file
UnitTests/test_hierarchical_clustering.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_hierarchical_clustering.cpp.s
.PHONY : UnitTests/test_hierarchical_clustering.cpp.s

UnitTests/test_random_walks.o: UnitTests/test_random_walks.cpp.o
.PHONY : UnitTests/test_random_walks.o

# target to build an object file
UnitTests/test_random_walks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_random_walks.cpp.o
.PHONY : UnitTests/test_random_walks.cpp.o

UnitTests/test_random_walks.i: UnitTests/test_random_walks.cpp.i
.PHONY : UnitTests/test_random_walks.i

# target to preprocess a source file
UnitTests/test_random_walks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_random_walks.cpp.i
.PHONY : UnitTests/test_random_walks.cpp.i

UnitTests/test_random_walks.s: UnitTests/test_random_walks.cpp.s
.PHONY : UnitTests/test_random_walks.s

# target to generate assembly for a file
UnitTests/test_random_walks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_random_walks.cpp.s
.PHONY : UnitTests/test_random_walks.cpp.s

UnitTests/test_statistics.o: UnitTests/test_statistics.cpp.o
.PHONY : UnitTests/test_statistics.o

# target to build an object file
UnitTests/test_statistics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_statistics.cpp.o
.PHONY : UnitTests/test_statistics.cpp.o

UnitTests/test_statistics.i: UnitTests/test_statistics.cpp.i
.PHONY : UnitTests/test_statistics.i

# target to preprocess a source file
UnitTests/test_statistics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_statistics.cpp.i
.PHONY : UnitTests/test_statistics.cpp.i

UnitTests/test_statistics.s: UnitTests/test_statistics.cpp.s
.PHONY : UnitTests/test_statistics.s

# target to generate assembly for a file
UnitTests/test_statistics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/UnitTests/test_statistics.cpp.s
.PHONY : UnitTests/test_statistics.cpp.s

Utils/clustering_utils.o: Utils/clustering_utils.cpp.o
.PHONY : Utils/clustering_utils.o

# target to build an object file
Utils/clustering_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/clustering_utils.cpp.o
.PHONY : Utils/clustering_utils.cpp.o

Utils/clustering_utils.i: Utils/clustering_utils.cpp.i
.PHONY : Utils/clustering_utils.i

# target to preprocess a source file
Utils/clustering_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/clustering_utils.cpp.i
.PHONY : Utils/clustering_utils.cpp.i

Utils/clustering_utils.s: Utils/clustering_utils.cpp.s
.PHONY : Utils/clustering_utils.s

# target to generate assembly for a file
Utils/clustering_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/clustering_utils.cpp.s
.PHONY : Utils/clustering_utils.cpp.s

Utils/exceptions.o: Utils/exceptions.cpp.o
.PHONY : Utils/exceptions.o

# target to build an object file
Utils/exceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/exceptions.cpp.o
.PHONY : Utils/exceptions.cpp.o

Utils/exceptions.i: Utils/exceptions.cpp.i
.PHONY : Utils/exceptions.i

# target to preprocess a source file
Utils/exceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/exceptions.cpp.i
.PHONY : Utils/exceptions.cpp.i

Utils/exceptions.s: Utils/exceptions.cpp.s
.PHONY : Utils/exceptions.s

# target to generate assembly for a file
Utils/exceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/exceptions.cpp.s
.PHONY : Utils/exceptions.cpp.s

Utils/hypothesis_testing.o: Utils/hypothesis_testing.cpp.o
.PHONY : Utils/hypothesis_testing.o

# target to build an object file
Utils/hypothesis_testing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/hypothesis_testing.cpp.o
.PHONY : Utils/hypothesis_testing.cpp.o

Utils/hypothesis_testing.i: Utils/hypothesis_testing.cpp.i
.PHONY : Utils/hypothesis_testing.i

# target to preprocess a source file
Utils/hypothesis_testing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/hypothesis_testing.cpp.i
.PHONY : Utils/hypothesis_testing.cpp.i

Utils/hypothesis_testing.s: Utils/hypothesis_testing.cpp.s
.PHONY : Utils/hypothesis_testing.s

# target to generate assembly for a file
Utils/hypothesis_testing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/hypothesis_testing.cpp.s
.PHONY : Utils/hypothesis_testing.cpp.s

Utils/map_utils.o: Utils/map_utils.cpp.o
.PHONY : Utils/map_utils.o

# target to build an object file
Utils/map_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/map_utils.cpp.o
.PHONY : Utils/map_utils.cpp.o

Utils/map_utils.i: Utils/map_utils.cpp.i
.PHONY : Utils/map_utils.i

# target to preprocess a source file
Utils/map_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/map_utils.cpp.i
.PHONY : Utils/map_utils.cpp.i

Utils/map_utils.s: Utils/map_utils.cpp.s
.PHONY : Utils/map_utils.s

# target to generate assembly for a file
Utils/map_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/map_utils.cpp.s
.PHONY : Utils/map_utils.cpp.s

Utils/pca_utils.o: Utils/pca_utils.cpp.o
.PHONY : Utils/pca_utils.o

# target to build an object file
Utils/pca_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/pca_utils.cpp.o
.PHONY : Utils/pca_utils.cpp.o

Utils/pca_utils.i: Utils/pca_utils.cpp.i
.PHONY : Utils/pca_utils.i

# target to preprocess a source file
Utils/pca_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/pca_utils.cpp.i
.PHONY : Utils/pca_utils.cpp.i

Utils/pca_utils.s: Utils/pca_utils.cpp.s
.PHONY : Utils/pca_utils.s

# target to generate assembly for a file
Utils/pca_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/pca_utils.cpp.s
.PHONY : Utils/pca_utils.cpp.s

Utils/profiling_utils.o: Utils/profiling_utils.cpp.o
.PHONY : Utils/profiling_utils.o

# target to build an object file
Utils/profiling_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/profiling_utils.cpp.o
.PHONY : Utils/profiling_utils.cpp.o

Utils/profiling_utils.i: Utils/profiling_utils.cpp.i
.PHONY : Utils/profiling_utils.i

# target to preprocess a source file
Utils/profiling_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/profiling_utils.cpp.i
.PHONY : Utils/profiling_utils.cpp.i

Utils/profiling_utils.s: Utils/profiling_utils.cpp.s
.PHONY : Utils/profiling_utils.s

# target to generate assembly for a file
Utils/profiling_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/profiling_utils.cpp.s
.PHONY : Utils/profiling_utils.cpp.s

Utils/random_utils.o: Utils/random_utils.cpp.o
.PHONY : Utils/random_utils.o

# target to build an object file
Utils/random_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/random_utils.cpp.o
.PHONY : Utils/random_utils.cpp.o

Utils/random_utils.i: Utils/random_utils.cpp.i
.PHONY : Utils/random_utils.i

# target to preprocess a source file
Utils/random_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/random_utils.cpp.i
.PHONY : Utils/random_utils.cpp.i

Utils/random_utils.s: Utils/random_utils.cpp.s
.PHONY : Utils/random_utils.s

# target to generate assembly for a file
Utils/random_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/random_utils.cpp.s
.PHONY : Utils/random_utils.cpp.s

Utils/read_files_utils.o: Utils/read_files_utils.cpp.o
.PHONY : Utils/read_files_utils.o

# target to build an object file
Utils/read_files_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/read_files_utils.cpp.o
.PHONY : Utils/read_files_utils.cpp.o

Utils/read_files_utils.i: Utils/read_files_utils.cpp.i
.PHONY : Utils/read_files_utils.i

# target to preprocess a source file
Utils/read_files_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/read_files_utils.cpp.i
.PHONY : Utils/read_files_utils.cpp.i

Utils/read_files_utils.s: Utils/read_files_utils.cpp.s
.PHONY : Utils/read_files_utils.s

# target to generate assembly for a file
Utils/read_files_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/read_files_utils.cpp.s
.PHONY : Utils/read_files_utils.cpp.s

Utils/set_utils.o: Utils/set_utils.cpp.o
.PHONY : Utils/set_utils.o

# target to build an object file
Utils/set_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/set_utils.cpp.o
.PHONY : Utils/set_utils.cpp.o

Utils/set_utils.i: Utils/set_utils.cpp.i
.PHONY : Utils/set_utils.i

# target to preprocess a source file
Utils/set_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/set_utils.cpp.i
.PHONY : Utils/set_utils.cpp.i

Utils/set_utils.s: Utils/set_utils.cpp.s
.PHONY : Utils/set_utils.s

# target to generate assembly for a file
Utils/set_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/set_utils.cpp.s
.PHONY : Utils/set_utils.cpp.s

Utils/sk_divergence_utils.o: Utils/sk_divergence_utils.cpp.o
.PHONY : Utils/sk_divergence_utils.o

# target to build an object file
Utils/sk_divergence_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/sk_divergence_utils.cpp.o
.PHONY : Utils/sk_divergence_utils.cpp.o

Utils/sk_divergence_utils.i: Utils/sk_divergence_utils.cpp.i
.PHONY : Utils/sk_divergence_utils.i

# target to preprocess a source file
Utils/sk_divergence_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/sk_divergence_utils.cpp.i
.PHONY : Utils/sk_divergence_utils.cpp.i

Utils/sk_divergence_utils.s: Utils/sk_divergence_utils.cpp.s
.PHONY : Utils/sk_divergence_utils.s

# target to generate assembly for a file
Utils/sk_divergence_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/sk_divergence_utils.cpp.s
.PHONY : Utils/sk_divergence_utils.cpp.s

Utils/stats_utils.o: Utils/stats_utils.cpp.o
.PHONY : Utils/stats_utils.o

# target to build an object file
Utils/stats_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/stats_utils.cpp.o
.PHONY : Utils/stats_utils.cpp.o

Utils/stats_utils.i: Utils/stats_utils.cpp.i
.PHONY : Utils/stats_utils.i

# target to preprocess a source file
Utils/stats_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/stats_utils.cpp.i
.PHONY : Utils/stats_utils.cpp.i

Utils/stats_utils.s: Utils/stats_utils.cpp.s
.PHONY : Utils/stats_utils.s

# target to generate assembly for a file
Utils/stats_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/stats_utils.cpp.s
.PHONY : Utils/stats_utils.cpp.s

Utils/vector_utils.o: Utils/vector_utils.cpp.o
.PHONY : Utils/vector_utils.o

# target to build an object file
Utils/vector_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/vector_utils.cpp.o
.PHONY : Utils/vector_utils.cpp.o

Utils/vector_utils.i: Utils/vector_utils.cpp.i
.PHONY : Utils/vector_utils.i

# target to preprocess a source file
Utils/vector_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/vector_utils.cpp.i
.PHONY : Utils/vector_utils.cpp.i

Utils/vector_utils.s: Utils/vector_utils.cpp.s
.PHONY : Utils/vector_utils.s

# target to generate assembly for a file
Utils/vector_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/Utils/vector_utils.cpp.s
.PHONY : Utils/vector_utils.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FASTER.dir/build.make CMakeFiles/FASTER.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FASTER"
	@echo "... Communities/Communities.o"
	@echo "... Communities/Communities.i"
	@echo "... Communities/Communities.s"
	@echo "... Communities/Community.o"
	@echo "... Communities/Community.i"
	@echo "... Communities/Community.s"
	@echo "... Communities/CommunityPrinter.o"
	@echo "... Communities/CommunityPrinter.i"
	@echo "... Communities/CommunityPrinter.s"
	@echo "... Graphs/HierarchicalClusterer.o"
	@echo "... Graphs/HierarchicalClusterer.i"
	@echo "... Graphs/HierarchicalClusterer.s"
	@echo "... Graphs/HyperGraph.o"
	@echo "... Graphs/HyperGraph.i"
	@echo "... Graphs/HyperGraph.s"
	@echo "... Graphs/UndirectedGraph.o"
	@echo "... Graphs/UndirectedGraph.i"
	@echo "... Graphs/UndirectedGraph.s"
	@echo "... RandomWalker/NodeClusterRandomWalkData.o"
	@echo "... RandomWalker/NodeClusterRandomWalkData.i"
	@echo "... RandomWalker/NodeClusterRandomWalkData.s"
	@echo "... RandomWalker/NodeRandomWalkData.o"
	@echo "... RandomWalker/NodeRandomWalkData.i"
	@echo "... RandomWalker/NodeRandomWalkData.s"
	@echo "... RandomWalker/RandomWalker.o"
	@echo "... RandomWalker/RandomWalker.i"
	@echo "... RandomWalker/RandomWalker.s"
	@echo "... UnitTests/run_all_tests.o"
	@echo "... UnitTests/run_all_tests.i"
	@echo "... UnitTests/run_all_tests.s"
	@echo "... UnitTests/test_clustering.o"
	@echo "... UnitTests/test_clustering.i"
	@echo "... UnitTests/test_clustering.s"
	@echo "... UnitTests/test_communities.o"
	@echo "... UnitTests/test_communities.i"
	@echo "... UnitTests/test_communities.s"
	@echo "... UnitTests/test_graphs.o"
	@echo "... UnitTests/test_graphs.i"
	@echo "... UnitTests/test_graphs.s"
	@echo "... UnitTests/test_hierarchical_clustering.o"
	@echo "... UnitTests/test_hierarchical_clustering.i"
	@echo "... UnitTests/test_hierarchical_clustering.s"
	@echo "... UnitTests/test_random_walks.o"
	@echo "... UnitTests/test_random_walks.i"
	@echo "... UnitTests/test_random_walks.s"
	@echo "... UnitTests/test_statistics.o"
	@echo "... UnitTests/test_statistics.i"
	@echo "... UnitTests/test_statistics.s"
	@echo "... Utils/clustering_utils.o"
	@echo "... Utils/clustering_utils.i"
	@echo "... Utils/clustering_utils.s"
	@echo "... Utils/exceptions.o"
	@echo "... Utils/exceptions.i"
	@echo "... Utils/exceptions.s"
	@echo "... Utils/hypothesis_testing.o"
	@echo "... Utils/hypothesis_testing.i"
	@echo "... Utils/hypothesis_testing.s"
	@echo "... Utils/map_utils.o"
	@echo "... Utils/map_utils.i"
	@echo "... Utils/map_utils.s"
	@echo "... Utils/pca_utils.o"
	@echo "... Utils/pca_utils.i"
	@echo "... Utils/pca_utils.s"
	@echo "... Utils/profiling_utils.o"
	@echo "... Utils/profiling_utils.i"
	@echo "... Utils/profiling_utils.s"
	@echo "... Utils/random_utils.o"
	@echo "... Utils/random_utils.i"
	@echo "... Utils/random_utils.s"
	@echo "... Utils/read_files_utils.o"
	@echo "... Utils/read_files_utils.i"
	@echo "... Utils/read_files_utils.s"
	@echo "... Utils/set_utils.o"
	@echo "... Utils/set_utils.i"
	@echo "... Utils/set_utils.s"
	@echo "... Utils/sk_divergence_utils.o"
	@echo "... Utils/sk_divergence_utils.i"
	@echo "... Utils/sk_divergence_utils.s"
	@echo "... Utils/stats_utils.o"
	@echo "... Utils/stats_utils.i"
	@echo "... Utils/stats_utils.s"
	@echo "... Utils/vector_utils.o"
	@echo "... Utils/vector_utils.i"
	@echo "... Utils/vector_utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

